spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost:13306/interpark?serverTimezone=UTC&characterEncoding=UTF-8
    username: prod
    password: 1234

  jpa:
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size : 1000
        ddl-auto: create